"""
Django settings for leave project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-9d1!_uq(s9lz!dfi=s701rrvekt^a9%)ua1))_jv3f_w+8b2ko'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'db_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'app.middleware.ForcePasswordChangeMiddleware',  # (หลัง messages)
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'leave.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.load_site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'leave.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eleave_db',         # ชื่อฐานข้อมูล
        'USER': 'root',               # ชื่อผู้ใช้ของ MySQL (ค่าเริ่มต้นมักจะเป็น 'root')
        'PASSWORD': '',  # รหัสผ่านของ MySQL
        'HOST': '127.0.0.1',          # หรือ 'localhost'
        'PORT': '3306',               # Port มาตรฐานของ MySQL
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'th'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'app:login'
LOGIN_REDIRECT_URL = 'app:dashboard'
LOGOUT_REDIRECT_URL = 'app:login'

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# --- Email Settings ---
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'commusic66@gmail.com'
EMAIL_HOST_PASSWORD = 'bnla ovdx qdfk mhvj' 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- Development/Testing Settings ---
# ==============================================================================
# ===== จุดที่แก้ไข: เพิ่มอีเมลสำหรับทดสอบ =====
# เมื่อ DEBUG = True อีเมลทั้งหมดจะถูกส่งไปยังที่อยู่นี้แทน
ADMIN_EMAIL = 'commusic66@gmail.com'
# --- Line Messaging API Settings ---
# ==============================================================================
# วาง Channel Access Token ที่ได้จาก Line Developers Console ที่นี่
LINE_CHANNEL_ACCESS_TOKEN = 'RaIJYRzSOTH4GOEK0CBQ8l192kqS+5U5+fGwcvBk8py35XAi6sdIktcZM5/C34jz/Od4TKw+xDVjd038bdVbpkxkVwD8Wk7PWpfCYk2SBLD42vyzr3fkDqx0S2FJQlelqrEZgq1Ac73kLJp91jSgagdB04t89/1O/w1cDnyilFU='

# ID นี้จะใช้รับการแจ้งเตือนทั้งหมดเมื่อ DEBUG = True
LINE_TEST_USER_ID = 'Uc533199e2c2c614aa8a1b2a566616b3e' 
# -------------------------
# --- Development/Testing Settings ---