# Generated by Django 5.2.5 on 2025-10-02 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=255)),
                ('position_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, to='app.position')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Info Requested', 'รอข้อมูลเพิ่มเติม')], default='Pending', max_length=20)),
                ('leave_date', models.DateField(default=django.utils.timezone.now)),
                ('leave_duration', models.CharField(choices=[('3 ชั่วโมง', '3 ชั่วโมง'), ('ครึ่งวัน', 'ครึ่งวัน'), ('เต็มวัน', 'เต็มวัน')], default='3 ชั่วโมง', max_length=10)),
                ('request_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_approver_role', models.CharField(default='manager', max_length=20)),
                ('info_request_comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='InOutHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_out_histories', to='app.employee')),
                ('guard', models.ForeignKey(db_column='guard_id', limit_choices_to={'role__role_name__iexact': 'security'}, on_delete=django.db.models.deletion.CASCADE, related_name='guard_histories', to='app.employee')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='app.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_order', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_time', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='app.leaverequest')),
            ],
        ),
    ]
