# Generated by Django 5.2.5 on 2025-10-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='employee',
        ),
        migrations.AlterField(
            model_name='inouthistory',
            name='guard',
            field=models.ForeignKey(db_column='guard_id', limit_choices_to={'role__role_name': 'Safety'}, on_delete=django.db.models.deletion.CASCADE, related_name='guard_histories', to='app.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='status',
            field=models.CharField(choices=[('Approved', 'อนุมัติ'), ('Rejected', 'ปฏิเสธ'), ('Pending', 'รอการดำเนินการ')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='inouthistory',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='leave_histories', to='app.employee'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_time', models.TimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'รออนุมัติ'), ('Approved', 'อนุมัติแล้ว'), ('Rejected', 'ถูกปฏิเสธ')], default='Pending', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('current_approver_role', models.CharField(choices=[('manager', 'รอผู้จัดการ'), ('supervisor', 'รอหัวหน้างาน'), ('hr_safety', 'รอ HR/Safety'), ('completed', 'เสร็จสิ้น')], default='manager', max_length=20)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='app.leaverequest'),
        ),
        migrations.AlterField(
            model_name='inouthistory',
            name='request',
            field=models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, to='app.leaverequest'),
        ),
        migrations.DeleteModel(
            name='SecurityGuard',
        ),
        migrations.DeleteModel(
            name='Complain',
        ),
    ]
