# Generated by Django 5.2.5 on 2025-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_leaverequest_attachment_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
