# Generated by Django 5.2.5 on 2025-10-02 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_complain_employee_alter_inouthistory_guard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='request_time',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_duration',
            field=models.CharField(choices=[('3_hours', '3 ชั่วโมง'), ('half_day', 'ครึ่งวัน'), ('full_day', 'เต็มวัน')], default='3_hours', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='request_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='current_approver_role',
            field=models.CharField(choices=[('manager', 'รออนุมัติจากผู้จัดการ'), ('supervisor', 'รออนุมัติจากหัวหน้างาน'), ('hr_safety', 'รออนุมัติจาก HR/Safety'), ('completed', 'เสร็จสิ้น')], default='manager', max_length=20),
        ),
    ]
