# Generated by Django 5.2.7 on 2025-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inouthistory',
            name='status',
            field=models.CharField(choices=[('OUT', 'อยู่ข้างนอก'), ('COMPLETED', 'กลับมาแล้ว')], default='OUT', max_length=10, null=True),
        ),
    ]
