# Generated by Django 5.2.5 on 2025-11-07 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_inouthistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=255, verbose_name='ชื่อผู้มาติดต่อ')),
                ('contact_person', models.CharField(max_length=255, verbose_name='ติดต่อใคร (พนักงาน/แผนก)')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='เหตุผล/บริษัท')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาเข้า')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='เวลาออก')),
                ('status', models.CharField(choices=[('IN', 'อยู่ในพื้นที่'), ('OUT', 'ออกไปแล้ว')], default='IN', max_length=10)),
                ('guard', models.ForeignKey(db_column='guard_id', limit_choices_to={'role__role_name__iexact': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs_recorded', to='app.employee')),
            ],
        ),
    ]
