# Generated by Django 5.2.5 on 2025-11-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inouthistory',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='return_images/', verbose_name='ภาพถ่ายการกลับเข้า'),
        ),
    ]
