# Generated by Django 5.2.5 on 2025-11-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inouthistory_return_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='ต้องเปลี่ยนรหัสผ่าน'),
        ),
    ]
