# Generated by Django 5.2.5 on 2025-11-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employee_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='delegate_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_tasks', to='app.employee', verbose_name='ผู้รับมอบอำนาจแทน'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='สถานะลาหยุด'),
        ),
    ]
