# Generated by Django 5.2.5 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employee_delegate_approver_employee_is_on_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_on_leave',
        ),
        migrations.AddField(
            model_name='employee',
            name='delegate_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการมอบอำนาจ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='delegate_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มมอบอำนาจ'),
        ),
    ]
